---
- name: Allocate swap file (MB)
  become: yes
  command: dd if=/dev/zero of="{{ item.dest }}" bs=1M count="{{ item.size }}"
  args: 
    creates: "{{ item.dest }}"
  with_items: 
    - { size: "{{ swap_size }}", dest: "{{ swap_file }}" }

- name: Format the files for swap
  become: yes
  command: mkswap "{{ swap_file }}"

- name: Change swap file permissions
  become: yes
  file: 
    path: "{{ swap_file }}"
    owner: root
    group: root
    mode: 0600

- name: Add the file to the system as a swap file
  become: yes
  command: swapon "{{ swap_file }}"

- name: Write swap entry in fstab
  become: yes
  mount: 
    name: none
    src: "{{ swap_file }}"
    fstype: swap
    opts: sw
    passno: "0"
    dump: "0"
    state: present
