---
- name: MYSQL | Get user from icingaweb2 DB
  command: > 
    mysql -h {{ icinga2_web2_db_host }}
      -P {{ icinga2_web2_db_port }}
      -u{{ icinga2_web2_db_user }}
      -p{{ icinga2_web2_db_pass }}
      {{ icinga2_web2_db }}
      --execute="SELECT * FROM icingaweb_user"
      --batch --skip-column-names
  no_log: True
  changed_when: False
  register:  mysql_icingaweb_users

- set_fact: 
    icingaweb_user_does_not_exist: true
  when: (mysql_icingaweb_users.stdout is defined) and (mysql_icingaweb_users.stdout == "")
