---
- name: restart icinga2
  become: yes
  service:
    name: icinga2
    state: restarted

- name: restart npcd
  become: yes
  service:
    name: npcd
    state: restarted

- name: reload httpd
  become: yes
  service:
    name: httpd
    state: reloaded
