---
# Admin user
pgsql_db_admin_username: postgres
pgsql_db_admin_password: postgres
pgsql_db_port: 5432
# Listen addresses on DB server
pgsql_db_listen_addresses: '*'
# DB's Authorization (see pg_hba.conf.j2)
pgsql_authorizations: 
 - { type: host, database: all, user: all, address: 127.0.0.1/32, method: ident }
 - { type: host, database: all, user: all, address: '::1/128', method: ident }
#pgsql_authorizations: 
# - { type: host, database: all, user: all, address: 127.0.0.1/32, method: ident }
# - { type: host, database: all, user: all, address: '::1/128', method: ident }
# - { type: host, database: all, user: postgres, address: 127.0.0.1/32, method: trust }
# - { type: host, database: all, user: postgres, address: 127.0.0.1/32, method: trust, when: some_condition_is_true }