---
# handlers file for icinga2-ansible-web2-ui
- name: restart icinga2
  service: 
    name: icinga2
    state: restarted
    enabled: yes

- name: reload httpd
  become: yes
  service:
    name: httpd
    state: reloaded