---
# Example of playbook for RedHat family only
- hosts: icinga2-web2-postgres
  roles:
   - role: epel-release
   - role: selinux
   - role: firewalld
   - role: swap
     # See host_vars/icinga2-web2-postgres.yml for postgresql-9.4-server config
   - role: postgresql-9.4-server
   - { role: php, become: yes }
   - { role: icinga2-nrpe-agent, tags: icinga2-nrpe-agent }
   - { role: icinga2-ansible-no-ui, become: yes, tags: icinga2-no-ui }
   - { role: icinga2-ansible-web2-ui, become: yes, tags: icinga2-ansible-web2-ui }
   - { role: icinga2-pnp4nagios, tags: icinga2-pnp4nagios }
   - { role: icinga2-ansible-custom-config-example, tags: icinga2-ansible-custom-config-example }
