---
# Example of playbook for RedHat family only
- hosts: monitoring_servers
  roles:
   - role: epel-release
   - role: selinux
   - role: firewalld
   - role: mariadb-server
     when: (icinga2_ido_backend == 'mysql' or icinga2_web2_backend == 'mysql')
   - { role: php, become: yes }
   - role: icinga2-ansible-no-ui
     become: yes

     icinga2_conf_global: |
       include "constants.conf"
       include "zones.conf"
       include <itl>
       include <plugins>
       include "features-enabled/*.conf"
       include_recursive "conf.d"
     check_commands:
       check_nrpe: |
          "-H", "$address$",
              "-c", "$remote_nrpe_command$",
     tags: icinga2-no-ui
   - { role: icinga2-ansible-web2-ui, become: yes, tags: icinga2-ansible-web2-ui }
