---
# Example of playbook for RedHat family only
- hosts: monitoring_servers
  roles:
   - role: epel-release
   - role: selinux
   - role: firewalld
   - role: swap
   - role: mariadb-server
   - { role: php, become: yes }
   - { role: icinga2-ansible-no-ui, become: yes, tags: icinga2-no-ui }
   - { role: icinga2-ansible-web2-ui, become: yes, tags: icinga2-ansible-web2-ui }
