---
- name: Install NRPE and Nagios plugins
  become: yes
  yum:
    name: "{{ item }}"
    state: latest
  with_items: nrpe_agent_packages_to_install
  tags:
   - nrpe_agent_install

- name: Configure NRPE agent
  become: yes
  template:
    src: nrpe.cfg.j2
    dest: "{{ nrpe_agent_config }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  register: nrpe_config
  tags:
   - nrpe_agent_config

- name: Open NRPE server port
  become: yes
  firewalld:
    port: "{{ nrpe_agent_port }}/tcp"
    permanent: true
    immediate: yes
    state: enabled
