---
- name: Install NRPE and Nagios plugins
  become: yes
  portage: 
    package: "{{ item }}"
    state: present
    update: yes
  with_items: nrpe_agent_packages_to_install
  tags:
   - nrpe_agent_install

- name: Configure NRPE agent
  become: yes
  template: 
    src: nrpe.cfg.j2
    dest: "{{ nrpe_agent_config }}"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
   - restart nrpe
  tags:
   - nrpe_agent_config
