---
- name: Install Icinga Web2 on RedHat OS family
  yum:
    name: "{{ item.package }}"
    state: latest
    enablerepo: "{{ enablerepo }}"
  with_items: icinga2_web2_ui_rpm
  tags: icinga2-ansible-web2-ui-install
  register: icinga2_web2_ui_rpm

- include: icinga2_web2_ui_RedHat_install_ido_mysql.yml
  when: icinga2_ido_backend == 'mysql'

- include: icinga2_web2_ui_RedHat_install_web2_mysql.yml
  when: icinga2_web2_backend == 'mysql'

- name: Ensure httpd enabled
  become: yes
  service:
    name: httpd
    enabled: yes

- name: Ensure httpd started
  become: yes
  service: 
    name: httpd
    state: started

- name: Open Icinga Web2 port
  become: yes
  firewalld:
    port: "{{ item }}/tcp"
    permanent: true
    immediate: yes
    state: enabled
  with_items:
    - "{{ icinga2_web2_ui_port }}"
