---
- name: Install MySQL-python on RedHat OS family
  yum:
    name: MySQL-python
    state: latest

- name: Install Icinga2 IDO modules on RedHat OS family
  yum:
    name: icinga2-ido-mysql
    state: latest

# ---------Icinga2 IDO DB

- name: Create a Database for Icinga2
  mysql_db:
    name: "{{ icinga2_ido_db }}"
    login_user: "{{ icinga2_ido_db_admin_user }}"
    login_password: "{{ icinga2_ido_db_admin_pass }}"
    login_host: "{{ icinga2_ido_db_host }}"
    login_port: "{{ icinga2_ido_db_port }}"
    state: present
  register: icinga_ido_db

- name: Create Icinga Database User and configure Grants
  mysql_user:
    name: "{{ icinga2_ido_db }}"
    password: "{{ icinga2_ido_db_pass }}"
    login_user: "{{ icinga2_ido_db_admin_user }}"
    login_password: "{{ icinga2_ido_db_admin_pass }}"
    login_host: "{{ icinga2_ido_db_host }}"
    login_port: "{{ icinga2_ido_db_port }}"
    state: present
    priv: "{{ icinga2_ido_db }}.*:GRANT,INSERT,SELECT,UPDATE,DELETE,DROP,CREATE VIEW,INDEX,EXECUTE"

- name: Import the IDO Schema on Icinga Web Database - RH6 (only once)
  mysql_db:
    name: "{{ icinga2_ido_db }}"
    login_user: "{{ icinga2_ido_db_admin_user }}"
    login_password: "{{ icinga2_ido_db_admin_pass }}"
    login_host: "{{ icinga2_ido_db_host }}"
    login_port: "{{ icinga2_ido_db_port }}"
    state: import
    target: "{{ icinga2_ido_mysql_schema_rh_6 }}"
  when: icinga_ido_db.changed

- name: Configure Icinga2 Ido Mysql Feature
  template:
    src: ido-mysql.conf.j2
    dest: "{{ icinga2_ido_mysql_conf }}"
    backup: yes
    owner: icinga
    group: icinga

- name: Enable Icinga2 Ido Mysql Feature
  command: "icinga2 feature enable ido-mysql"
  register: features_result
  changed_when: "'for these changes to take effect' in features_result.stdout"
  notify:
   - restart icinga2
