---
# See https://github.com/Icinga/icingaweb2/blob/master/doc/installation.md

- name: Create icingaweb2 group
  become: yes
  group:
    name: icingaweb2
    state: present
    system: yes

- name: Ensure users are members of groups
  user:
    name: "{{ item.name }}"
    append: yes
    groups: "{{ item.groups }}"
  with_items:
    - { name: httpd, groups: 'icingaweb2' }
    - { name: apache, groups: 'icingacmd,nagios,icingaweb2' }
    - { name: "{{ icinga2_user }}", groups: 'icingacmd,nagios' }
  notify: 
  - restart icinga2

- name: Create some directories
  become: yes
  file:
    path: "{{ item }}"
    state: directory
    owner: apache
    group: icingaweb2
    mode: 0770
  with_items:
    - "{{ icinga2_web2_conf_dir }}/modules"
    - "{{ icinga2_web2_conf_dir }}/modules/monitoring"
    - "{{ icinga2_web2_conf_dir }}/enabledModules"

- include: icinga2_web2_ui_configure_with_wizard.yml
  when: icinga2_web2_setup_with_wizard

- include: icinga2_web2_ui_configure_without_wizard.yml
  when: not icinga2_web2_setup_with_wizard
