---
- include: icinga2_web2_ui_RedHat_install.yml

- include: icinga2_web2_ui_RedHat_configure.yml

- include: icinga2_web2_ui_configure_with_wizard.yml
  when: icinga2_web2_setup_with_wizard

- include: icinga2_web2_ui_configure_without_wizard.yml
  when: not icinga2_web2_setup_with_wizard

- include: icinga2_web2_ui_RedHat_selinux.yml
