---
# See https://github.com/Icinga/icingaweb2/blob/master/doc/installation.md

# We likely don't want to run this setup twice since it can mess up any configuration you may have done from the UI.
# So the idea is to check if we have a user created in the DB, if it is the case then we skip the setup.
# We can force to reinstate with extra_vars icinga2_web2_setup_reinstate=true, but at your own risk, really!

# When setup is done we supposed to have a user created. Let's check that:
- include: icinga2_web2_ui_get_icingaweb_user.yml

- name: Enable Icingaweb2's modules
  become: yes
  file:
    state: link
    src: "{{ item.src }}"
    path: "{{ item.path }}"
    owner: apache
    group: icingaweb2
  with_items:
    - { src: /usr/share/icingaweb2/modules/monitoring, path: /etc/icingaweb2/enabledModules/monitoring }
  when: (icingaweb_users.stdout == "") or icinga2_web2_setup_reinstate

- name: Configure Icinga Web 2
  become: yes
  template: 
    src: "{{ item }}.j2"
    dest: "/etc/icingaweb2/{{ item }}"
    backup: yes
    owner: apache
    group: icingaweb2
    mode: 0660
  with_items: 
    - resources.ini
    - config.ini
    - authentication.ini
    - roles.ini
    - groups.ini
    - modules/monitoring/backends.ini
    - modules/monitoring/commandtransports.ini
    - modules/monitoring/config.ini
  notify: restart icinga2
  when: (icingaweb_users.stdout == "") or icinga2_web2_setup_reinstate
