---
- name: Install MySQL-python on RedHat OS family
  yum:
    name: MySQL-python
    state: latest

# ---------Icingaweb2 DB

- name: Create a Database for Icingaweb2
  mysql_db: 
    name: "{{ icinga2_web2_db }}"
    login_user: "{{ icinga2_web2_db_admin_user }}"
    login_password: "{{ icinga2_web2_db_admin_pass }}"
    login_host: "{{ icinga2_web2_db_host }}"
    login_port: "{{ icinga2_web2_db_port }}"
    state: present
  register: icinga_web2_db

- name: Create Icingaweb2 Database User and configure Grants
  mysql_user:
    name: "{{ icinga2_web2_db }}"
    password: "{{ icinga2_web2_db_pass }}"
    login_user: "{{ icinga2_web2_db_admin_user }}"
    login_password: "{{ icinga2_web2_db_admin_pass }}"
    login_host: "{{ icinga2_web2_db_host }}"
    login_port: "{{ icinga2_web2_db_port }}"
    state: present
    priv: "{{ icinga2_web2_db }}.*:ALL,GRANT"

- name: Import the Icingaweb2 Schema on Icinga Web Database
  mysql_db:
    name: "{{ icinga2_web2_db }}"
    login_user: "{{ icinga2_web2_db_admin_user }}"
    login_password: "{{ icinga2_web2_db_admin_pass }}"
    login_host: "{{ icinga2_web2_db_host }}"
    login_port: "{{ icinga2_web2_db_port }}"
    state: import
    target: "{{ icinga2_web2_mysql_schema_rh_6 }}"
  when: icinga_web2_db.changed
