---
# tasks file for icinga2-ansible-web2-ui

- include: icinga2_web2_ui_RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: icinga2_web2_ui_create_admin_user.yml
  when: not icinga2_web2_setup_with_wizard
